const KEY="nutritrack_fresh_v1";
const GOALS={calories:2000,protein:[110,130],carbs:270,fat:55,fiber:[20,25],calcium:1000,magnesium:350,iron:8,potassium:3500,vitaminC:75,vitaminB12:2.4,vitaminD:15,omega3:1600};
const N=[['calories','Calories','kcal'],['protein','Protein','g'],['carbs','Carbs','g'],['fat','Fat','g'],['fiber','Fiber','g'],['calcium','Calcium','mg'],['magnesium','Magnesium','mg'],['iron','Iron','mg'],['potassium','Potassium','mg'],['vitaminC','Vitamin C','mg'],['vitaminB12','Vitamin B12','µg'],['vitaminD','Vitamin D','µg'],['omega3','Omega-3','mg']];
const $=id=>document.getElementById(id), today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const base={profile:{age:19,height:164,weight:72,sex:'male',activityLevel:'moderate'}};let state={...base};
try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)state={...base,...x,profile:{...base.profile,...(x.profile||{})}}}catch(e){console.error(e)}
const save=()=>localStorage.setItem(KEY,JSON.stringify(state)), date=()=>$("selectedDate").value||today();
function day(){if(!state[date()])state[date()]={foods:[],activities:[],steps:0,weight:null};const d=state[date()];d.foods??=[];d.activities??=[];return d}
const num=id=>parseFloat($(id)?.value)||0, fmt=(n,d=1)=>(Number(n)||0).toFixed(d).replace(/\.0+$/,''), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function energy(){const p=state.profile,w=+p.weight,h=+p.height,a=+p.age;if(!(w&&h&&a))return 2000;const b=p.sex==='female'?10*w+6.25*h-5*a-161:10*w+6.25*h-5*a+5;return Math.round(b*({sedentary:1.2,light:1.375,moderate:1.55,very:1.725}[p.activityLevel]||1.55))}
function renderProfile(){const p=state.profile;[['profileAge',p.age],['profileHeight',p.height],['profileWeight',p.weight],['profileSex',p.sex],['activityLevel',p.activityLevel]].forEach(([id,v])=>{if($(id))$(id).value=v});[['displayAge',p.age||'—'],['displayHeight',p.height||'—'],['displayWeight',p.weight||'—'],['displaySex',p.sex==='female'?'Female':p.sex==='male'?'Male':'—'],['displayCalorieReference',energy()]].forEach(([id,v])=>{if($(id))$(id).textContent=v})}
function totals(){const t=Object.fromEntries(N.map(([k])=>[k,0]));day().foods.forEach(f=>N.forEach(([k])=>t[k]+=+f[k]||0));return t}
function renderOverview(){const t=totals(),s=$("dailySummary"),g=$("nutrientGrid");if(!s||!g)return;const pct=(v,m)=>Math.min(100,Math.max(0,v/m*100));s.innerHTML=`<article><div class="label">CALORIES</div><div class="value">${fmt(t.calories,0)} kcal</div><div class="sub">Goal 2000 • ${fmt(Math.max(0,2000-t.calories),0)} remaining</div><div class="bar"><i style="width:${pct(t.calories,2000)}%"></i></div></article><article><div class="label">PROTEIN</div><div class="value">${fmt(t.protein)} g</div><div class="sub">Goal 110–130 g • ${t.protein<110?fmt(110-t.protein)+' g more':'goal range reached'}</div><div class="bar"><i style="width:${pct(t.protein,110)}%"></i></div></article><article><div class="label">CARBS</div><div class="value">${fmt(t.carbs)} g</div><div class="sub">Goal 270 g • ${fmt(Math.max(0,270-t.carbs))} g remaining</div><div class="bar"><i style="width:${pct(t.carbs,270)}%"></i></div></article><article><div class="label">FAT</div><div class="value">${fmt(t.fat)} g</div><div class="sub">Goal 55 g • ${fmt(Math.max(0,55-t.fat))} g remaining</div><div class="bar"><i style="width:${pct(t.fat,55)}%"></i></div></article>`;
g.innerHTML=N.map(([k,l,u])=>{const v=t[k],goal=GOALS[k],min=Array.isArray(goal)?goal[0]:goal,max=Array.isArray(goal)?goal[1]:goal,need=Math.max(0,min-v),status=Array.isArray(goal)?(v<min?`Need ${fmt(need)} ${u} more`:v<=max?'Within goal range':`Above range by ${fmt(v-max)} ${u}`):(v>=min?'Goal reached':`Need ${fmt(need)} ${u} more`);return `<article class="nutrient"><div class="label">${l}</div><div class="value">${fmt(v,k==='calories'?0:1)} <small>${u}</small></div><div class="target">Goal: ${Array.isArray(goal)?`${min}–${max}`:min} ${u}</div><div class="target">${status}</div><div class="bar"><i style="width:${pct(v,min)}%"></i></div></article>`}).join('')}
function renderMeals(){const box=$("mealList"),groups=['Breakfast','Lunch','Snack','Dinner','Other'];let html='';groups.forEach(m=>{const list=day().foods.map((f,i)=>({...f,i})).filter(f=>f.meal===m);if(!list.length)return;const mt=list.reduce((a,f)=>(a.calories+=+f.calories||0,a.protein+=+f.protein||0,a.carbs+=+f.carbs||0,a.fat+=+f.fat||0,a.fiber+=+f.fiber||0,a),{calories:0,protein:0,carbs:0,fat:0,fiber:0});html+=`<div class="meal"><div class="meal-title">${m}<small> • ${fmt(mt.calories,0)} kcal • P ${fmt(mt.protein)}g • C ${fmt(mt.carbs)}g • F ${fmt(mt.fat)}g • Fiber ${fmt(mt.fiber)}g</small></div>${list.map(f=>`<div class="food"><span><strong>${esc(f.name)}</strong><br><small>${fmt(f.quantity)} ${esc(f.unit)}</small></span><span>${fmt(f.calories,0)} kcal</span><span>P ${fmt(f.protein)}g</span><span>C ${fmt(f.carbs)}g</span><span>F ${fmt(f.fat)}g</span><span>Fib ${fmt(f.fiber)}g</span><button class="delete" onclick="deleteFood(${f.i})">Delete</button></div>`).join('')}</div>`});box.innerHTML=html||'<p>No food added for this date. Add your first meal above.</p>'}
function renderActivity(){const d=day();if($("steps"))$("steps").value=d.steps||'';$("activityList").innerHTML=d.activities.length?d.activities.map((a,i)=>`<div class="activity"><span><b>${esc(a.type)}</b> • ${fmt(a.duration,0)} min • ${fmt(a.distance)} km</span><button class="delete" onclick="deleteActivity(${i})">Delete</button></div>`).join(''):'<p>No activity recorded.</p>'}
function renderWeight(){const d=day();if($("weightInput"))$("weightInput").value=d.weight?.value||'';if($("displayWeight"))$("displayWeight").textContent=d.weight?.value??state.profile.weight??'—';const e=Object.entries(state).filter(([k,v])=>k!=='profile'&&v?.weight).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,10);$("weightHistory").innerHTML=e.length?e.map(([date,v])=>`<div class="weight"><span>${date}<br><small>${esc(v.weight.note||'')}</small></span><b>${fmt(v.weight.value)} kg</b></div>`).join(''):'<p>No weight history yet.</p>'}
function render(){renderProfile();renderOverview();renderMeals();renderActivity();renderWeight()}
$("profileForm").addEventListener('submit',e=>{e.preventDefault();state.profile={age:num('profileAge'),height:num('profileHeight'),weight:num('profileWeight'),sex:$('profileSex').value,activityLevel:$('activityLevel').value};save();render();alert('Profile saved successfully.')});
$("foodForm").addEventListener('submit',e=>{e.preventDefault();const name=$('foodName').value.trim(),q=num('quantity');if(!name||q<=0){alert('Food name aur quantity enter karo.');return}const f={meal:$('meal').value,name,quantity:q,unit:$('unit').value};N.forEach(([k])=>f[k]=num(k));day().foods.push(f);save();e.target.reset();$('meal').value='Breakfast';$('unit').value='g';['protein','carbs','fat','fiber','calcium','magnesium','iron','potassium','vitaminC','vitaminB12','vitaminD','omega3'].forEach(id=>$(id).value=0);render()});
$("clearFood").addEventListener('click',()=>$("foodForm").reset());
$("activityForm").addEventListener('submit',e=>{e.preventDefault();const d=day();d.steps=num('steps');d.activities.push({type:$('activityType').value,duration:num('duration'),distance:num('distance')});save();render();e.target.reset()});
$("weightForm").addEventListener('submit',e=>{e.preventDefault();const w=num('weightInput');if(w<=0)return;day().weight={value:w,note:$('weightNote').value.trim()};state.profile.weight=w;save();render();$('weightNote').value='' });
$("selectedDate").addEventListener('change',render);function deleteFood(i){if(confirm('Delete this food?')){day().foods.splice(i,1);save();render()}}function deleteActivity(i){if(confirm('Delete this activity?')){day().activities.splice(i,1);save();render()}}
$('selectedDate').value=today();render();